website/__init__.py
from flask import Flask
from datetime import datetime
import os


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = os.getenv("PORTFOLIO_FLASK_SECRET_KEY")
    app.url_map.strict_slashes = False

    app.jinja_env.globals.update(
        current_year=datetime.now().year,
        my_name=os.getenv("MY_NAME"),
        my_email=os.getenv("MY_EMAIL"),
    )

    from .views import views

    app.register_blueprint(views, url_prefix="/")

    return app

website/views.py
from flask import Blueprint, render_template


views = Blueprint("views", __name__)


@views.route("/")
def home():

    data_dict = {
        "title": "Alex Kanavos",
        "author": "Alex Kanavos",
        "description": "Portfolio",
    }

    return render_template("index.html", data=data_dict)


@views.route("/about")
def about():

    data_dict = {
        "title": "About | Alex Kanavos",
        "author": "Alex Kanavos",
        "description": "About | Alex Kanavos",
    }

    return render_template("about.html", data=data_dict)


@views.app_errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404

website/templates/about.html
{% extends 'base.html' %}

{% block title %}{{ data.title }}{% endblock title %}

{% block author %}{{ data.author }}{% endblock author %}
{% block description %}{{ data.description }}{% endblock description %}
{% block keywords %}{% endblock keywords %}

{% block twtitle %}{{ data.title }}{% endblock twtitle %}
{% block twdescription %}{{ data.description }}{% endblock twdescription %}

{% block ogtitle %}{{ data.title }}{% endblock ogtitle %}
{% block ogdescription %}{{ data.description }}{% endblock ogdescription %}

{% block content %}

<article class="post-single">
    <header class="post-header">
        <div class="breadcrumbs"><a href="{{ url_for('views.home') }}">Home</a>&nbsp;»&nbsp;<a
                href="{{ url_for('views.about') }}/">About</a></div>
        <h1 class="post-title entry-hint-parent">
            About
        </h1>
    </header>
    <div class="post-content">
        <p>I'm Alex, originally from Athens and currently living in Berlin. Although I have an engineering background
            and
            hold a Diploma in Civil Engineering, I have shifted my focus towards software development. Inspired by the
            vibrant tech scene in Berlin, I've delved into programming, totally loving the problem-solving and
            creativity it
            brings to the table.</p>
        <p>Apart from my portfolio, this is a place where I plan to showcase my adventures in software development and
            data
            science. That said, as I build and upgrade this platform I will probably add some blogging functionality to
            it
            as well. So until then, stay tuned.</p>
        Cheerio!
        <hr>
        <h2 id="contact-about">Wanna get in touch?<a hidden="" class="anchor" aria-hidden="true"
                href="#contact-about">#</a></h2>
        <p>Drop me an email: <a href="mailto:{{ my_email }}" target="_blank">alex [at] alexkanavos [dot] com</a>
        </p>
    </div>

</article>

{% endblock content %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="auto">

<head>

    <meta name="portfolio" content="Personal Website">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow">

    <title>{% block title %}{% endblock title %}</title>

    <meta name="author" content="{% block author %}{% endblock author %}">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
    <link rel="canonical" href="{{ request.url }}">

    <!-- CSS -->
    <link rel="preload stylesheet" crossorigin="anonymous" type="text/css"
        href="{{ url_for('static', filename='css/styles.css') }}" as="style">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180"
        href="{{ url_for('static', filename='assets/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{{ url_for('static', filename='assets/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16"
        href="{{ url_for('static', filename='assets/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='assets/favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='assets/favicon/safari-pinned-tab.svg') }}"
        color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Twitter -->
    <meta name="twitter:title" content="{% block twtitle %}{% endblock twtitle %}">
    <meta name="twitter:description" content="{% block twdescription %}{% endblock twdescription %}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="{{ url_for('static', filename='assets/img/desk_beach.png') }}">

    <!-- Opengraph -->
    <meta property="og:type" content="website gia to index, article gia to article">
    <meta property="og:title" content="{% block ogtitle %}{% endblock ogtitle %}">
    <meta property="og:description" content="{% block ogdescription %}{% endblock ogdescription %}">
    <meta property="og:url" content="{{ request.url }}">
    <meta property="og:image" content="{{ url_for('static', filename='assets/img/desk_beach.png') }}">

    <noscript>
        <style>
            #theme-toggle,
            .top-link {
                display: none;
            }
        </style>
        <style>
            @media (prefers-color-scheme: dark) {
                :root {
                    --theme: rgb(29, 30, 32);
                    --entry: rgb(46, 46, 51);
                    --primary: rgb(218, 218, 219);
                    --secondary: rgb(155, 156, 157);
                    --tertiary: rgb(65, 66, 68);
                    --content: rgb(196, 196, 197);
                    --code-block-bg: rgb(46, 46, 51);
                    --code-bg: rgb(55, 56, 62);
                    --border: rgb(51, 51, 51);
                }

                .list {
                    background: var(--theme);
                }

                .list:not(.dark)::-webkit-scrollbar-track {
                    background: 0 0;
                }

                .list:not(.dark)::-webkit-scrollbar-thumb {
                    border-color: var(--theme);
                }
            }
        </style>
    </noscript>

</head>

<body class="{% block body_class %}{% endblock body_class %}" id="top">

    {% include "header.html" %}

    <main class="main">

        {% block content %}{% endblock content %}

    </main>

    {% include "footer.html" %}

    <script crossorigin="anonymous" type="text/javascript"
        src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>

</html>

website/templates/footer.html
<footer class="footer">
    <span>&copy; {{ current_year }} {{ my_name }}. All Rights Reserved.</span>
</footer>

<a href="#top" aria-label="go to top" title="Go to Top (Alt + G)" class="top-link" id="top-link" accesskey="g"
    style="visibility: hidden; opacity: 0;">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentColor">
        <path d="M12 6H0l6-6z"></path>
    </svg>
</a>

website/templates/header.html
<header class="header">
    <nav class="nav">
        <div class="logo">
            <a href="{{ url_for('views.home') }}" accesskey="h" title="{{ my_name }} (Alt + H)">{{ my_name }}</a>
            <div class="logo-switches">
                <button id="theme-toggle" accesskey="t" title="(Alt + T)">
                    <svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
                    </svg>
                    <svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <circle cx="12" cy="12" r="5"></circle>
                        <line x1="12" y1="1" x2="12" y2="3"></line>
                        <line x1="12" y1="21" x2="12" y2="23"></line>
                        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
                        <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
                        <line x1="1" y1="12" x2="3" y2="12"></line>
                        <line x1="21" y1="12" x2="23" y2="12"></line>
                        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
                        <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
                    </svg>
                </button>
            </div>
        </div>
        <ul id="menu">
            <li>
                <a href="{{ url_for('views.about') }}/" title="About">
                    <span>About</span>
                </a>
            </li>
        </ul>
    </nav>
</header>

website/templates/mono_index.html
<!-- JSchema Markup Generator (JSON-LD) H ALLIWS PYTHON LIBRARY JSONSCHEMA-->
<!-- Organisation -->



<!-- body class="list dark" id="top" !!!!!!!!!!!!!!!!!!!! -->

<!-- mesa sto main class apo base -->

<article class="first-entry home-info">
    <header class="entry-header">
        <h1>PaperMod’s Demo</h1>
    </header>
    <div class="entry-content">
        <p>👋 Welcome to demo page of Hugo's theme PaperMod!</p>
        <ul>
            <li><strong>PaperMod</strong> is designed to be clean and simple but fast and responsive theme with
                useful feature-set that enhances UX.</li>
            <li>Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends
                and social media .</li>
            <li>PaperMod is based on theme <a
                    href="https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3">Paper</a>.
            </li>
        </ul>

    </div>
    <footer class="entry-footer">
        <div class="social-icons">
            <a href="https://github.com/adityatelange/hugo-PaperMod" target="_blank" rel="noopener noreferrer me"
                title="View Source on Github">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path
                        d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22">
                    </path>
                </svg>
            </a>
            <a href="https://discord.gg/ahpmTvhVmp" target="_blank" rel="noopener noreferrer me"
                title="Join Discord Community">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 127.14 96.36" fill="currentColor" stroke="none"
                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path
                        d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.79,32.65-1.71,56.6.54,80.21h0A105.73,105.73,0,0,0,32.71,96.36,77.7,77.7,0,0,0,39.6,85.25a68.42,68.42,0,0,1-10.85-5.18c.91-.66,1.8-1.34,2.66-2a75.57,75.57,0,0,0,64.32,0c.87.71,1.76,1.39,2.66,2a68.68,68.68,0,0,1-10.87,5.19,77,77,0,0,0,6.89,11.1A105.25,105.25,0,0,0,126.6,80.22h0C129.24,52.84,122.09,29.11,107.7,8.07ZM42.45,65.69C36.18,65.69,31,60,31,53s5-12.74,11.43-12.74S54,46,53.89,53,48.84,65.69,42.45,65.69Zm42.24,0C78.41,65.69,73.25,60,73.25,53s5-12.74,11.44-12.74S96.23,46,96.12,53,91.08,65.69,84.69,65.69Z">
                    </path>
                </svg>
            </a>
            <a href="https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&amp;url=https://github.com/adityatelange/hugo-PaperMod&amp;hashtags=Hugo,PaperMod"
                target="_blank" rel="noopener noreferrer me" title="Share PaperMod on X/Twitter">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                    <path
                        d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z">
                    </path>
                </svg>
            </a>
            <a href="https://ko-fi.com/adityatelange" target="_blank" rel="noopener noreferrer me"
                title="Buy Me a Ko-Fi :)">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                    preserveAspectRatio="xMidYMid meet" viewBox="0 -3 23 27" fill="none" stroke="currentColor"
                    stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
                    <path
                        d="M23.881 8.948c-.773-4.085-4.859-4.593-4.859-4.593H.723c-.604 0-.679.798-.679.798s-.082 7.324-.022 11.822c.164 2.424 2.586 2.672 2.586 2.672s8.267-.023 11.966-.049c2.438-.426 2.683-2.566 2.658-3.734c4.352.24 7.422-2.831 6.649-6.916zm-11.062 3.511c-1.246 1.453-4.011 3.976-4.011 3.976s-.121.119-.31.023c-.076-.057-.108-.09-.108-.09c-.443-.441-3.368-3.049-4.034-3.954c-.709-.965-1.041-2.7-.091-3.71c.951-1.01 3.005-1.086 4.363.407c0 0 1.565-1.782 3.468-.963c1.904.82 1.832 3.011.723 4.311zm6.173.478c-.928.116-1.682.028-1.682.028V7.284h1.77s1.971.551 1.971 2.638c0 1.913-.985 2.667-2.059 3.015z">
                    </path>
                </svg>
            </a>
        </div>

    </footer>
</article>

<article class="post-entry">
    <header class="entry-header">
        <h2 class="entry-hint-parent">Install / Update PaperMod
        </h2>
    </header>
    <div class="entry-content">
        <p>Read aboout Install and Update instructions and sampled configuration templates</p>
    </div>
    <footer class="entry-footer"><span title="2021-01-20 00:00:00 +0000 UTC">January 20,
            2021</span>&nbsp;·&nbsp;5 min&nbsp;·&nbsp;Aditya Telange</footer>
    <a class="entry-link" aria-label="post link to Install / Update PaperMod"
        href="https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/"></a>
</article>

<article class="post-entry">
    <header class="entry-header">
        <h2 class="entry-hint-parent">Features / Mods
        </h2>
    </header>
    <div class="entry-content">
        <p>Learn About All Features in PaperMod</p>
    </div>
    <footer class="entry-footer"><span title="2021-01-20 00:00:00 +0000 UTC">January 20,
            2021</span>&nbsp;·&nbsp;7 min&nbsp;·&nbsp;Aditya Telange</footer>
    <a class="entry-link" aria-label="post link to Features / Mods"
        href="https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/"></a>
</article>

<article class="post-entry">
    <header class="entry-header">
        <h2 class="entry-hint-parent">FAQs / How To's Guide
            <span class="entry-hint" title="Draft">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 -960 960 960" fill="currentColor">
                    <path
                        d="M160-410v-60h300v60H160Zm0-165v-60h470v60H160Zm0-165v-60h470v60H160Zm360 580v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q9 9 13 20t4 22q0 11-4.5 22.5T862.09-380L643-160H520Zm300-263-37-37 37 37ZM580-220h38l121-122-18-19-19-18-122 121v38Zm141-141-19-18 37 37-18-19Z">
                    </path>
                </svg>
            </span>
        </h2>
    </header>
    <div class="entry-content">
        <p>We’ll try to answer frequently asked qestions by users.</p>
    </div>
    <footer class="entry-footer"><span title="2021-01-20 00:00:00 +0000 UTC">January 20,
            2021</span>&nbsp;·&nbsp;4 min&nbsp;·&nbsp;PaperMod Contributors</footer>
    <a class="entry-link" aria-label="post link to FAQs / How To's Guide"
        href="https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/"></a>
</article>

<article class="post-entry">
    <header class="entry-header">
        <h2 class="entry-hint-parent">Social-Icons / Share-Icons
            <span class="entry-hint" title="Draft">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 -960 960 960" fill="currentColor">
                    <path
                        d="M160-410v-60h300v60H160Zm0-165v-60h470v60H160Zm0-165v-60h470v60H160Zm360 580v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q9 9 13 20t4 22q0 11-4.5 22.5T862.09-380L643-160H520Zm300-263-37-37 37 37ZM580-220h38l121-122-18-19-19-18-122 121v38Zm141-141-19-18 37 37-18-19Z">
                    </path>
                </svg>
            </span>
        </h2>
    </header>
    <div class="entry-content">
        <p>List of all Icons supported by PaperMod</p>
    </div>
    <footer class="entry-footer"><span title="2021-01-20 00:00:00 +0000 UTC">January 20,
            2021</span>&nbsp;·&nbsp;2 min&nbsp;·&nbsp;Aditya Telange</footer>
    <a class="entry-link" aria-label="post link to Social-Icons / Share-Icons"
        href="https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/"></a>
</article>

<article class="post-entry">
    <header class="entry-header">
        <h2 class="entry-hint-parent">Variables | Front Matter
            <span class="entry-hint" title="Draft">
                <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 -960 960 960" fill="currentColor">
                    <path
                        d="M160-410v-60h300v60H160Zm0-165v-60h470v60H160Zm0-165v-60h470v60H160Zm360 580v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q9 9 13 20t4 22q0 11-4.5 22.5T862.09-380L643-160H520Zm300-263-37-37 37 37ZM580-220h38l121-122-18-19-19-18-122 121v38Zm141-141-19-18 37 37-18-19Z">
                    </path>
                </svg>
            </span>
        </h2>
    </header>
    <div class="entry-content">
        <p>List of Front Matter variables used by PaperMod</p>
    </div>
    <footer class="entry-footer"><span title="2021-01-20 00:00:00 +0000 UTC">January 20,
            2021</span>&nbsp;·&nbsp;6 min&nbsp;·&nbsp;Aditya Telange</footer>
    <a class="entry-link" aria-label="post link to Variables | Front Matter"
        href="https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/"></a>
</article>

<!-- footer gia 2h selida -->

<footer class="page-footer">
    <nav class="pagination">
        <a class="next" href="https://adityatelange.github.io/hugo-PaperMod/page/2/">Next&nbsp;2/2&nbsp;»
        </a>
    </nav>
</footer>